# Skeletonization configuration

teasar_params:
  scale: 0.3
  const: 50
  pdrf_scale: 100000
  pdrf_exponent: 4
  soma_detection_threshold: 999999
  soma_acceptance_threshold: 999999
  soma_invalidation_scale: 2
  soma_invalidation_const: 300
  max_paths: null

dust_threshold: 500
anisotropy: [1, 1, 1]    # voxel anisotropy (Z, Y, X)
fix_branching: true
fix_borders: true
progress: true
parallel: 1
postprocess_dust_threshold: 1000
postprocess_tick_threshold: 0
keep_largest_component_only: true

# Length analysis configuration
analysis:
  output_json: true
  output_labeled_tif: true
  branch_point_radius: 1
